name: YAML Lint
description: Run YAML Lint validation
inputs:
  path:
    description: File(s) or directory
    required: false
runs.pre:
  using: "composite"
  steps:
    - run: echo "${{ secrets.JFROG_PASSWORD }}" | docker login docker.pkg.github.com -u "${{ secrets.JFROG_USER }}" --password-stdin
      shell: bash
runs:
  using: docker
  image: docker://casf-docker-prod-local.jfrog.teliacompany.io/casf-docker-prod-local/telia-company/yaml-lint-docker
  env:
    GITHUB_ACTIONS: "true"
    GITHUB_WORKFLOW: "{{ github.workflow.name }}"
    INPUT_CONFIG_FILE: ${{ inputs.path }}
